<?xml version="1.0" encoding="utf-8" ?>
<description xmlns="http://www.w3.org/ns/wsdl"
             targetNamespace="http://jw.nju.edu.cn/wsdl/error"
             xmlns:score="http://jw.nju.edu.cn/schema/scorelist"
             xmlns:sid="http://jw.nju.edu.cn/schema/studentid"
             xmlns:course="http://jw.nju.edu.cn/schema/course"
             xmlns:stu="http://jw.nju.edu.cn/schema/student">

    <types xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <xs:import namespace="http://jw.nju.edu.cn/schema/scorelist"
                   schemaLocation="https://raw.githubusercontent.com/JiawaHawKodomo/SOA_assignment/master/ScoreList.xsd"/>
        <xs:import namespace="http://jw.nju.edu.cn/schema/studentid"
                   schemaLocation="https://raw.githubusercontent.com/JiawaHawKodomo/SOA_assignment/master/StudentId.xsd"/>
        <xs:import namespace="http://jw.nju.edu.cn/schema/course"
                   schemaLocation="https://raw.githubusercontent.com/JiawaHawKodomo/SOA_assignment/master/Course.xsd"/>
    </types>


    <interface name="errors">
        <fault name="invalidDataError">
            <documentation>数据格式错误</documentation>
        </fault>
        <fault name="noFoundScoreTypeError">
            <documentation>成绩类型或课程编号不存在</documentation>
        </fault>
        <fault name="duplicateInsertScoreError">
            <documentation>该课程成绩类型已存在</documentation>
        </fault>
    </interface>
</description>